import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const nav = "p-2"
  const active = "bg-white text-black font-bold"
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="m-5 flex gap-4 justify-center">
          <Link className={nav} href="/" >Home</Link>
          <Link className={nav} href="/streaming">Streaming</Link>
          <Link className={nav} href="/github_user">Dynamic routes</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
